package testing

var _isRecordingOrEvaluatingFixtures = false

// IsRecordingOrEvaluatingFixtures can be used to run code required to control any
// external sources of randomness that can affect fixtures.
//
// Use this sparingly, we don't want to introduce too much drift between our test
// environment and production.
//
// Note: This is only needed to control *external* sources of randomness. Any random
// values generated by the tester should use tester_utils.random, which uses a fixed
// seed across all test runs.
func IsRecordingOrEvaluatingFixtures() bool {
	return _isRecordingOrEvaluatingFixtures
}
